name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run type-check

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Build application
      run: npm run build
      env:
        MONGODB_URI: mongodb://localhost:27017/test
        JWT_SECRET: test-secret-key-for-ci-cd-pipeline-testing-only
        JWT_EXPIRES_IN: 7d
        ADMIN_EMAIL: test@example.com
        ADMIN_PASSWORD: test123
        MAX_FILE_SIZE: 5242880
        UPLOAD_DIR: public/uploads/projects
        NODE_ENV: production
        NEXT_PUBLIC_APP_URL: http://localhost:3000

    - name: Check build output
      run: |
        if [ ! -d ".next" ]; then
          echo "Build failed - .next directory not found"
          exit 1
        fi
        echo "Build successful!"

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit (informational)
      run: |
        echo "Running security audit..."
        npm audit --audit-level=high || echo "Security vulnerabilities found - check Dependabot alerts"
        echo "Security audit completed"